/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tropes: Trope;
    genres: Genre;
    collections: Collection;
    books: Book;
    chapters: Chapter;
    series: Series;
    authors: Author;
    narrators: Narrator;
    litmobs: Litmob;
    'litmob-entries': LitmobEntry;
    follows: Follow;
    shelf: Shelf;
    users: User;
    pages: Page;
    media: Media;
    audio: Audio;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    tropes: {
      books: 'books';
    };
    books: {
      chapters: 'chapters';
    };
    series: {
      books: 'books';
    };
    authors: {
      books: 'books';
    };
    narrators: {
      books: 'books';
    };
    litmobs: {
      entries: 'litmob-entries';
    };
  };
  collectionsSelect: {
    tropes: TropesSelect<false> | TropesSelect<true>;
    genres: GenresSelect<false> | GenresSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    chapters: ChaptersSelect<false> | ChaptersSelect<true>;
    series: SeriesSelect<false> | SeriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    narrators: NarratorsSelect<false> | NarratorsSelect<true>;
    litmobs: LitmobsSelect<false> | LitmobsSelect<true>;
    'litmob-entries': LitmobEntriesSelect<false> | LitmobEntriesSelect<true>;
    follows: FollowsSelect<false> | FollowsSelect<true>;
    shelf: ShelfSelect<false> | ShelfSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    audio: AudioSelect<false> | AudioSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tropes".
 */
export interface Trope {
  id: number;
  title: string;
  kind: 'family' | 'trope' | 'refinement';
  family?: (number | Trope)[] | null;
  parent?: (number | null) | Trope;
  /**
   * Показывать только книги с озвучкой.
   */
  audioOnly?: boolean | null;
  /**
   * Раздел /18/ и возрастное окно.
   */
  adult?: boolean | null;
  related?: (number | Trope)[] | null;
  /**
   * Под названием в каталоге: «После развода, с генералом, попаданка».
   */
  subtitle?: string | null;
  /**
   * Пусто — берётся название.
   */
  h1?: string | null;
  /**
   * 2–3 предложения под главный запрос.
   */
  lead?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  mainQuery?: string | null;
  monthlyVolume?: number | null;
  /**
   * Например ×2,4 или «новый».
   */
  growth?: string | null;
  wave?: ('1' | '2' | '3' | '4') | null;
  /**
   * Через запятую.
   */
  phrases?: string | null;
  /**
   * Латиницей. Пусто — сгенерируется из названия.
   */
  slug?: string | null;
  /**
   * Если адрес вне своего раздела: /18/omegavers/, /audio/rasskazy/.
   */
  customPath?: string | null;
  /**
   * Вычисляется автоматически.
   */
  path?: string | null;
  published?: boolean | null;
  books?: {
    docs?: (number | Book)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  title: string;
  authors?: (number | Author)[] | null;
  narrators?: (number | Narrator)[] | null;
  /**
   * Только с разрешения правообладателя.
   */
  cover?: (number | null) | Media;
  /**
   * HEX, например #E9C7D2. Пока нет обложки — цветная плашка с сюжетом.
   */
  coverTint?: string | null;
  /**
   * Не копия аннотации — свой текст без спойлеров.
   */
  about?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Например: «Бывший пожалеет. ХЭ гарантирован».
   */
  hook?: string | null;
  series?: {
    ref?: (number | null) | Series;
    order?: number | null;
  };
  tropes?: (number | Trope)[] | null;
  genres?: (number | Genre)[] | null;
  status?: ('ongoing' | 'completed' | 'frozen') | null;
  happyEnding?: ('yes' | 'no' | 'unknown') | null;
  heat?: ('none' | 'moderate' | 'explicit') | null;
  warnings?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  hasAudio?: boolean | null;
  audioHours?: number | null;
  mode?: ('reference' | 'licensed') | null;
  externalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  freeChapters?: number | null;
  claimed?: boolean | null;
  isTranslation?: boolean | null;
  /**
   * Для запросов «[название] на русском».
   */
  originalTitle?: string | null;
  translator?: string | null;
  litmob?: (number | null) | Litmob;
  /**
   * Латиницей. Пусто — сгенерируется из названия.
   */
  slug?: string | null;
  /**
   * Вычисляется автоматически.
   */
  path?: string | null;
  published?: boolean | null;
  publishedAt?: string | null;
  /**
   * Вымышленная книга для проверки дизайна. Удаляется командой seed:demo -- --remove.
   */
  isDemo?: boolean | null;
  chapters?: {
    docs?: (number | Chapter)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  about?: string | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  user?: (number | null) | User;
  isDemo?: boolean | null;
  claimed?: boolean | null;
  /**
   * Латиницей. Пусто — сгенерируется из названия.
   */
  slug?: string | null;
  /**
   * Вычисляется автоматически.
   */
  path?: string | null;
  published?: boolean | null;
  books?: {
    docs?: (number | Book)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles?: ('admin' | 'editor' | 'author' | 'narrator' | 'reader')[] | null;
  adultConfirmedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    cover?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "narrators".
 */
export interface Narrator {
  id: number;
  name: string;
  photo?: (number | null) | Media;
  about?: string | null;
  /**
   * Например: «тёплый низкий женский».
   */
  voice?: string | null;
  demo?: (number | null) | Audio;
  genres?: (number | Genre)[] | null;
  user?: (number | null) | User;
  isDemo?: boolean | null;
  /**
   * Латиницей. Пусто — сгенерируется из названия.
   */
  slug?: string | null;
  /**
   * Вычисляется автоматически.
   */
  path?: string | null;
  published?: boolean | null;
  books?: {
    docs?: (number | Book)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio".
 */
export interface Audio {
  id: number;
  title?: string | null;
  durationSec?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres".
 */
export interface Genre {
  id: number;
  title: string;
  parent?: (number | null) | Genre;
  audioOnly?: boolean | null;
  adult?: boolean | null;
  tropes?: (number | Trope)[] | null;
  /**
   * Под названием в каталоге: «После развода, с генералом, попаданка».
   */
  subtitle?: string | null;
  /**
   * Пусто — берётся название.
   */
  h1?: string | null;
  /**
   * 2–3 предложения под главный запрос.
   */
  lead?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  mainQuery?: string | null;
  monthlyVolume?: number | null;
  /**
   * Например ×2,4 или «новый».
   */
  growth?: string | null;
  wave?: ('1' | '2' | '3' | '4') | null;
  /**
   * Через запятую.
   */
  phrases?: string | null;
  /**
   * Латиницей. Пусто — сгенерируется из названия.
   */
  slug?: string | null;
  /**
   * Если адрес вне своего раздела: /18/omegavers/, /audio/rasskazy/.
   */
  customPath?: string | null;
  /**
   * Вычисляется автоматически.
   */
  path?: string | null;
  published?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series".
 */
export interface Series {
  id: number;
  title: string;
  lead?: string | null;
  /**
   * Латиницей. Пусто — сгенерируется из названия.
   */
  slug?: string | null;
  /**
   * Вычисляется автоматически.
   */
  path?: string | null;
  published?: boolean | null;
  books?: {
    docs?: (number | Book)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "litmobs".
 */
export interface Litmob {
  id: number;
  title: string;
  organizer?: (number | null) | User;
  status?: ('draft' | 'moderation' | 'recruiting' | 'running' | 'voting' | 'finished' | 'rejected') | null;
  trope?: (number | null) | Trope;
  /**
   * Если подходящего сюжета нет в каталоге.
   */
  customTheme?: string | null;
  pitch: string;
  mustHave?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  forbidden?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  minChars?: number | null;
  maxChars?: number | null;
  rating?: ('general' | 'adult') | null;
  happyEndingRequired?: boolean | null;
  pov?: ('any' | 'first' | 'third') | null;
  applicationsUntil?: string | null;
  startAt?: string | null;
  firstChapterBy?: string | null;
  chaptersPerWeek?: number | null;
  finishAt?: string | null;
  maxParticipants?: number | null;
  joinMode?: ('open' | 'application' | 'invite') | null;
  badge?: (number | null) | Media;
  coverStyle?: string | null;
  narratorsWelcome?: boolean | null;
  readerVoting?: boolean | null;
  /**
   * Например: профессиональная озвучка победителя.
   */
  prize?: string | null;
  moderationNote?: string | null;
  /**
   * Латиницей. Пусто — сгенерируется из названия.
   */
  slug?: string | null;
  /**
   * Вычисляется автоматически.
   */
  path?: string | null;
  entries?: {
    docs?: (number | LitmobEntry)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "litmob-entries".
 */
export interface LitmobEntry {
  id: number;
  litmob: number | Litmob;
  author: number | User;
  synopsis?: string | null;
  book?: (number | null) | Book;
  status?: ('pending' | 'approved' | 'rejected' | 'dropped') | null;
  votes?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters".
 */
export interface Chapter {
  id: number;
  book: number | Book;
  order?: number | null;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  audio?: (number | null) | Audio;
  narrator?: (number | null) | Narrator;
  isFree?: boolean | null;
  published?: boolean | null;
  /**
   * По ней шлём «вышла прода».
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: number;
  title: string;
  /**
   * Под названием в каталоге: «После развода, с генералом, попаданка».
   */
  subtitle?: string | null;
  adult?: boolean | null;
  tropes?: (number | Trope)[] | null;
  genres?: (number | Genre)[] | null;
  audioOnly?: boolean | null;
  books?: (number | Book)[] | null;
  /**
   * Пусто — берётся название.
   */
  h1?: string | null;
  /**
   * 2–3 предложения под главный запрос.
   */
  lead?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  mainQuery?: string | null;
  monthlyVolume?: number | null;
  /**
   * Например ×2,4 или «новый».
   */
  growth?: string | null;
  wave?: ('1' | '2' | '3' | '4') | null;
  /**
   * Через запятую.
   */
  phrases?: string | null;
  /**
   * Латиницей. Пусто — сгенерируется из названия.
   */
  slug?: string | null;
  /**
   * Если адрес вне своего раздела: /18/omegavers/, /audio/rasskazy/.
   */
  customPath?: string | null;
  /**
   * Вычисляется автоматически.
   */
  path?: string | null;
  published?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "follows".
 */
export interface Follow {
  id: number;
  user: number | User;
  book?: (number | null) | Book;
  litmob?: (number | null) | Litmob;
  narrator?: (number | null) | Narrator;
  trope?: (number | null) | Trope;
  channel?: ('email' | 'push') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shelf".
 */
export interface Shelf {
  id: number;
  user: number | User;
  book: number | Book;
  status?: ('want' | 'listening' | 'done') | null;
  chapter?: (number | null) | Chapter;
  positionSec?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  section?: ('narrators' | 'authors' | 'article' | 'service') | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Пусто — берётся название.
   */
  h1?: string | null;
  /**
   * 2–3 предложения под главный запрос.
   */
  lead?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  mainQuery?: string | null;
  monthlyVolume?: number | null;
  /**
   * Например ×2,4 или «новый».
   */
  growth?: string | null;
  wave?: ('1' | '2' | '3' | '4') | null;
  /**
   * Через запятую.
   */
  phrases?: string | null;
  /**
   * Полный адрес, например /avtoram/kak-napisat-knigu/
   */
  path?: string | null;
  published?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tropes';
        value: number | Trope;
      } | null)
    | ({
        relationTo: 'genres';
        value: number | Genre;
      } | null)
    | ({
        relationTo: 'collections';
        value: number | Collection;
      } | null)
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'chapters';
        value: number | Chapter;
      } | null)
    | ({
        relationTo: 'series';
        value: number | Series;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'narrators';
        value: number | Narrator;
      } | null)
    | ({
        relationTo: 'litmobs';
        value: number | Litmob;
      } | null)
    | ({
        relationTo: 'litmob-entries';
        value: number | LitmobEntry;
      } | null)
    | ({
        relationTo: 'follows';
        value: number | Follow;
      } | null)
    | ({
        relationTo: 'shelf';
        value: number | Shelf;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'audio';
        value: number | Audio;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tropes_select".
 */
export interface TropesSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  family?: T;
  parent?: T;
  audioOnly?: T;
  adult?: T;
  related?: T;
  subtitle?: T;
  h1?: T;
  lead?: T;
  body?: T;
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  mainQuery?: T;
  monthlyVolume?: T;
  growth?: T;
  wave?: T;
  phrases?: T;
  slug?: T;
  customPath?: T;
  path?: T;
  published?: T;
  books?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres_select".
 */
export interface GenresSelect<T extends boolean = true> {
  title?: T;
  parent?: T;
  audioOnly?: T;
  adult?: T;
  tropes?: T;
  subtitle?: T;
  h1?: T;
  lead?: T;
  body?: T;
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  mainQuery?: T;
  monthlyVolume?: T;
  growth?: T;
  wave?: T;
  phrases?: T;
  slug?: T;
  customPath?: T;
  path?: T;
  published?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  adult?: T;
  tropes?: T;
  genres?: T;
  audioOnly?: T;
  books?: T;
  h1?: T;
  lead?: T;
  body?: T;
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  mainQuery?: T;
  monthlyVolume?: T;
  growth?: T;
  wave?: T;
  phrases?: T;
  slug?: T;
  customPath?: T;
  path?: T;
  published?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  title?: T;
  authors?: T;
  narrators?: T;
  cover?: T;
  coverTint?: T;
  about?: T;
  hook?: T;
  series?:
    | T
    | {
        ref?: T;
        order?: T;
      };
  tropes?: T;
  genres?: T;
  status?: T;
  happyEnding?: T;
  heat?: T;
  warnings?:
    | T
    | {
        text?: T;
        id?: T;
      };
  hasAudio?: T;
  audioHours?: T;
  mode?: T;
  externalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  freeChapters?: T;
  claimed?: T;
  isTranslation?: T;
  originalTitle?: T;
  translator?: T;
  litmob?: T;
  slug?: T;
  path?: T;
  published?: T;
  publishedAt?: T;
  isDemo?: T;
  chapters?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters_select".
 */
export interface ChaptersSelect<T extends boolean = true> {
  book?: T;
  order?: T;
  title?: T;
  body?: T;
  audio?: T;
  narrator?: T;
  isFree?: T;
  published?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series_select".
 */
export interface SeriesSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  slug?: T;
  path?: T;
  published?: T;
  books?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  about?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  user?: T;
  isDemo?: T;
  claimed?: T;
  slug?: T;
  path?: T;
  published?: T;
  books?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "narrators_select".
 */
export interface NarratorsSelect<T extends boolean = true> {
  name?: T;
  photo?: T;
  about?: T;
  voice?: T;
  demo?: T;
  genres?: T;
  user?: T;
  isDemo?: T;
  slug?: T;
  path?: T;
  published?: T;
  books?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "litmobs_select".
 */
export interface LitmobsSelect<T extends boolean = true> {
  title?: T;
  organizer?: T;
  status?: T;
  trope?: T;
  customTheme?: T;
  pitch?: T;
  mustHave?:
    | T
    | {
        text?: T;
        id?: T;
      };
  forbidden?:
    | T
    | {
        text?: T;
        id?: T;
      };
  minChars?: T;
  maxChars?: T;
  rating?: T;
  happyEndingRequired?: T;
  pov?: T;
  applicationsUntil?: T;
  startAt?: T;
  firstChapterBy?: T;
  chaptersPerWeek?: T;
  finishAt?: T;
  maxParticipants?: T;
  joinMode?: T;
  badge?: T;
  coverStyle?: T;
  narratorsWelcome?: T;
  readerVoting?: T;
  prize?: T;
  moderationNote?: T;
  slug?: T;
  path?: T;
  entries?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "litmob-entries_select".
 */
export interface LitmobEntriesSelect<T extends boolean = true> {
  litmob?: T;
  author?: T;
  synopsis?: T;
  book?: T;
  status?: T;
  votes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "follows_select".
 */
export interface FollowsSelect<T extends boolean = true> {
  user?: T;
  book?: T;
  litmob?: T;
  narrator?: T;
  trope?: T;
  channel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shelf_select".
 */
export interface ShelfSelect<T extends boolean = true> {
  user?: T;
  book?: T;
  status?: T;
  chapter?: T;
  positionSec?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  adultConfirmedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  section?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  h1?: T;
  lead?: T;
  body?: T;
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  mainQuery?: T;
  monthlyVolume?: T;
  growth?: T;
  wave?: T;
  phrases?: T;
  path?: T;
  published?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        cover?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio_select".
 */
export interface AudioSelect<T extends boolean = true> {
  title?: T;
  durationSec?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  adultGateText?: string | null;
  /**
   * Страница сюжета с меньшим числом книг закрыта от поиска (noindex).
   */
  minBooksToIndex?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  adultGateText?: T;
  minBooksToIndex?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}